using System.Collections.Generic;

namespace Mozgoslav.Api.GraphQL.Settings;

public sealed record UpdateSettingsInput(
    string VaultPath,
    string LlmProvider,
    string LlmEndpoint,
    string LlmModel,
    string LlmApiKey,
    string ObsidianApiHost,
    string ObsidianApiToken,
    string WhisperModelPath,
    string VadModelPath,
    string Language,
    string ThemeMode,
    int WhisperThreads,
    bool DictationEnabled,
    string DictationHotkeyType,
    int DictationMouseButton,
    string DictationKeyboardHotkey,
    string DictationLanguage,
    string DictationWhisperModelId,
    int DictationCaptureSampleRate,
    bool DictationLlmPolish,
    string DictationInjectMode,
    bool DictationOverlayEnabled,
    string DictationOverlayPosition,
    bool DictationSoundFeedback,
    IReadOnlyList<string> DictationVocabulary,
    int DictationModelUnloadMinutes,
    string DictationTempAudioPath,
    IReadOnlyDictionary<string, string> DictationAppProfiles,
    bool SyncthingEnabled,
    string SyncthingObsidianVaultPath,
    string SyncthingApiKey,
    string SyncthingBaseUrl,
    bool DictationPushToTalk = true,
    bool ObsidianFeatureEnabled = false,
    bool DictationDumpEnabled = false,
    string DictationDumpHotkeyToggle = "",
    string DictationDumpHotkeyHold = "",
    bool McpServerEnabled = false,
    int McpServerPort = 51051,
    string McpServerToken = "",
    bool ActionsSkillEnabled = false,
    bool RemindersSkillEnabled = false,
    bool DictationClassifyIntentEnabled = false,
    string ClaudeCliPath = "");
