namespace Mozgoslav.Domain.Entities;

/// <summary>
/// ADR-007 §2.6 BC-025 — routes notes generated by a given profile into a
/// specific vault folder (one of the <see cref="FolderMapping"/> entries by
/// alias). When <see cref="AutoApplyOnExport"/> is true, the export-all
/// endpoint moves the note on its first export; when false the rule only
/// seeds the folder picker default in the UI.
/// </summary>
public sealed record VaultExportRule(
    Guid Id,
    string SourceProfileId,
    string TargetFolderAlias,
    bool AutoApplyOnExport);
