using System;

namespace Mozgoslav.Domain.Entities;

/// ADR-007 §2.6 BC-025 — routes notes generated by a given profile into a
public sealed record VaultExportRule(
    Guid Id,
    string SourceProfileId,
    string TargetFolderAlias,
    bool AutoApplyOnExport);
